name: build devcontainer
on:
  workflow_dispatch:
  pull_request:
    paths:
      - .devcontainer/**
env:
  REGISTRY: ghcr.io
jobs:
  build-devcontainer:
    runs-on: [self-hosted, Linux, X64]
    container:
      image: docker:latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout merged branch
        uses: actions/checkout@v4
      - name: setup build environment
        run: |
          apk add --update nodejs npm python3 make g++
          npm install -g @devcontainers/cli
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build and upload the devcontainer image
        run: |
          devcontainer build --workspace-folder . --push true --image-name ${{ env.REGISTRY }}/rookro/tauri-template-devcontainer:latest
